[package]
name = "osiris"
version = "0.1.0"
authors = ["Derek Hendrickx <derek@hendrickx.me>"]

[dependencies]
hyper = "0.11.6"
futures = "0.1.17"
qstring = "0.5.2"
url = "1.6.0"
bip_bencode = "0.4.4"
byteorder = "1.1.0"
slog = "2.1.1"
slog-term = "2.3.0"
env_logger = "0.4.3"
