[package]
name = "osiris"
version = "0.1.0"
authors = ["Derek Hendrickx <derek@hendrickx.me>"]

[dependencies]
hyper = "0.12"
futures = "0.1"
qstring = "0.5"
url = "1.7"
bip_bencode = "0.4"
byteorder = "1.2"
log = "0.4"
pretty_env_logger = "0.2"
tokio = "0.1"
